baseURL = "https://rikimachine99.github.io"
languageCode = "en-us"
title = "Riccardo Marinelli"
theme = "dimension-hugo-theme"
[taxonomies]
    tag = "tag"
    category = "categories"
    mood = "moods" 

publishDir = "docs"